name: Deploy to DEV

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    envNOWFLAKE_USER }}    env:
      SNOWFLAKE_ACCOUNT: JKB05448
      SNOWFLAKE_USER: AAGRAWAL712
      SNOWFLAKE_PASSWORD: Googlehome@15
      SNOWFLAKE_WAREHOUSE: COMPUTE_WH
      SNOWFLAKE_ROLE: ACCOUNTADMIN
      TARGET_DATABASE: FIRST_TECH_DCU_D

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Snowflake Connector
        run: |
          pip install snowflake-connector-python

      - name: Execute customer.sql
        run: |
          python deploy.py
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
